import type { Metadata } from "next";
import { Raleway, Geist_Mono } from "next/font/google";
import "./globals.css";

import { FooterComponent } from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";


const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: ["300", "400", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${geistMono.variable}`}>
            <Navbar/> 
            <div className="main">
        {children}
         </div>
        <FooterComponent></FooterComponent>
      </body>
    </html>
  );
}
